#' @title Parse an Objective Description String
#'
#' @description
#'
#' Extracts structured metadata from a human-readable objective description
#' generated by `objective_term()`.
#' The function identifies:
#'
#' \itemize{
#'   \item the **objective type** ("Relative objective" or "Absolute objective"),
#'   \item the **attribute** being optimized,
#'   \item the **attribute type** ("Categorical" or "Quantitative"),
#'   \item the **application level** ("Module-level", "Pathway-level", "Panel-level"),
#'   \item the **operator** ("max" or "min"), if detectable from wording.
#' }
#'
#' @param obj_string A character string describing an objective, typically
#' produced internally by \code{objective_term()}.
#'
#' @return A list with elements:
#' \describe{
#'   \item{objective_type}{Character; "Relative objective", "Absolute objective", or NA}
#'   \item{attribute}{Character; extracted attribute name or NA}
#'   \item{attribute_type}{Character; "Categorical", "Quantitative", or NA}
#'   \item{level}{Character; "Module-level", "Pathway-level", "Panel-level", or NA}
#'   \item{operator}{Character; "max", "min", or NA}
#' }
#'
#' @keywords internal
#' @noRd

parse_objective_string <- function(obj_string) {
  stopifnot(is.character(obj_string), length(obj_string) == 1L)
  if (grepl("Relative Objective:", obj_string, ignore.case = TRUE)) {
    objective_type <- "Relative objective"
  } else if (grepl("Absolute Objective:", obj_string, ignore.case = TRUE)) {
    objective_type <- "Absolute objective"
  } else {
    objective_type <- NA_character_
  }

  if (grepl("Maximize", obj_string, ignore.case = TRUE)) {
    operator <- "(max)"
  } else if (grepl("Minimize", obj_string, ignore.case = TRUE)) {
    operator <- "(min)"
  } else {
    operator <- NA_character_
  }

  attribute <- NA_character_
  attribute_type <- NA_character_
  # quantitative pattern: "the sum of X values"
  if (grepl("the sum of .* values", obj_string, ignore.case = TRUE)) {
    attribute <- sub(".*the sum of (.*?) values.*", "\\1", obj_string)
    attribute <- trimws(attribute)
    attribute_type <- "Quantitative"
    # categorical pattern: "the number of items from category 'X'"
  } else if (grepl("the number of items", obj_string, ignore.case = TRUE)) {
    attribute <- sub(".*from\\s+(?:category\\s+'?([^'[:space:]]+)'?|([^'[:space:]]+)\\s+category).*",
                      "\\1\\2", obj_string,ignore.case = TRUE)
    attribute_type <- "Categorical"
  }

  application_level<-NA_character_
  if (grepl("\\bin\\s+a?\\s*panel\\b", obj_string, ignore.case = TRUE)) {
    application_level <- "Panel-level"
  } else if (grepl("\\bin\\s+module\\s+[0-9]+\\b", obj_string, ignore.case = TRUE)) {
    application_level <- "Module-level"
  } else if (grepl("\\bin\\s+pathway\\s+[0-9]+\\b", obj_string, ignore.case = TRUE)) {
    application_level<- "Pathway-level"
  }


  return(list(objective_type = objective_type,
              attribute      = attribute,
              attribute_type = attribute_type,
              application_level = application_level,
              operator = operator))
}

